name: mBox
author: StephanWagner
category: Interface
tags: [box, tooltip, modal, window, dialog, popup, notice, element]
docs: http://www.htmltweaks.com/mBox/Documentation
demo: http://www.htmltweaks.com/mBox
current: 0.1